### ISSUE TITLE
android app doesn't send photos

### ISSUE THREAD

**Issue by deeman30rus** [couchbaselabs/photo-drop#12]
send log

9269-10050/android.jamiltz.com.photodrop W/Sync﹕ Error converting lastSequence: null to long.  Using 0
9269-10061/android.jamiltz.com.photodrop E/RemoteRequest﹕ Got error status: 404 for http://192.168.43.111:5432/db/77cbe8b0-80f4-4cc0-adef-13ecd4205ecd?new_edits=false.  Reason: Not found

receive log

04-07 10:31:26.212  10569-10569/android.jamiltz.com.photodrop I/System.out﹕ Listening on :: http://192.168.43.89:5433/db
04-07 10:31:26.216  10569-10997/android.jamiltz.com.photodrop I/System.out﹕ [Thu Apr 07 10:31:26 GMT+03:00 2016] TJWS httpd :: - SimpleAcceptor ServerSocket[addr=::/::,port=0,localport=5433] is listening.
04-07 10:31:30.387  10569-11040/android.jamiltz.com.photodrop W/Listener﹕ authHeader is null
04-07 10:31:31.148  10569-11045/android.jamiltz.com.photodrop W/Listener﹕ authHeader is null
04-07 10:31:31.275  10569-11050/android.jamiltz.com.photodrop W/Listener﹕ authHeader is null
04-07 10:31:32.217  10569-11050/android.jamiltz.com.photodrop W/Router﹕ WARNING: Exception parsing body into dictionary
    com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
            at [Source: Acme.Serve.Serve$ServeInputStream@208190d; line: 1, column: 3]
            at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1486)
            at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
            at com.fasterxml.jackson.core.base.ParserBase.reportUnexpectedNumberChar(ParserBase.java:991)
            at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleInvalidNumberStart(UTF8StreamJsonParser.java:2610)
            at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseNegNumber(UTF8StreamJsonParser.java:1366)
            at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:784)
            at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697)
            at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3600)
            at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3545)
            at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)
            at com.couchbase.lite.router.Router.getBodyAsDictionary(Router.java:172)
            at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:1795)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.couchbase.lite.router.Router.start(Router.java:471)
            at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
            at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
            at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
            at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
            at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
            at java.lang.Thread.run(Thread.java:818)
04-07 10:31:32.230  10569-11050/android.jamiltz.com.photodrop E/Router﹕ Router unable to route request to do_PUT_Document
    java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Method.invoke(Native Method)
            at com.couchbase.lite.router.Router.start(Router.java:471)
            at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
            at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
            at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
            at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
            at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: com.couchbase.lite.CouchbaseLiteException
            at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:1797)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.couchbase.lite.router.Router.start(Router.java:471)
            at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
            at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
            at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
            at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
            at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
            at java.lang.Thread.run(Thread.java:818)

**Comment by hristo-stefanov** [comment]
I get the same error trying to sync between two physical Android devices. I think it is caused by https://github.com/couchbase/couchbase-lite-java-core/issues/617
Is it a device specific issue?
